### ISSUE TITLE
Any chance of updating this to the new npm repository?

### ISSUE THREAD

**Issue by randynwalsh** [mayflower/cordova-android-scrollbar#1]
http://plugins.cordova.io/npm/developers.html

Any chance of updating this to the new npm repository? This code has been very helpful!

Thank you.

**Comment by DirtyHairy** [comment]
Sure, I'll see what I can do as soon as I find time.

**Comment by randynwalsh** [comment]
Awesome.  Left me know when it's ready and I'll buy you a beer.

**Comment by randynwalsh** [comment]
Hi Christian,

Is there anything I can do to help out with this?  It would really help me
out.  Thanks!

Randy

**Comment by DirtyHairy** [comment]
Hi Randy,

Sorry for the long wait. I have updated the plugin; version 0.2.0 supports cordova-android >= 4.0.0 (thus dropping support for the 3.x.x series) and is published on NPM as cordova-android-scrollbar.

Cheers
    -Christian

**Comment by randynwalsh** [comment]
Hi Christian,

Thanks so much.  I was able to update my app and get it working again.  I'd
be happy to send you $10 to buy a beer if you have an address or paypal
email.

Either way - thanks again!

Randy

**Comment by DirtyHairy** [comment]
Hi Randy,

Glad to hear that it works for you. As for the beer business: I'll gladly stand up against prohibition if you paypal me via https://www.paypal.me/cnspeckn

Cheers
    -Christian Speckner
